export const IO_longPattern = {
  longPattern:{
    robot:1,
    current:{station:'',name:"无",times:'',count:'',status:5},
    queue:[
      {station:'',name:"无",times:'',count:'',status:5},
      {station:'',name:"无",times:'',count:'',status:5},
      {station:'',name:"无",times:'',count:'',status:5},
      {station:'',name:"无",times:'',count:'',status:5},
      {station:'',name:"无",times:'',count:'',status:5},
      {station:'',name:"无",times:'',count:'',status:5},
      {station:'',name:"无",times:'',count:'',status:5},
      {station:'',name:"无",times:'',count:'',status:5},
      {station:'',name:"无",times:'',count:'',status:5},
      {station:'',name:"无",times:'',count:'',status:5},
    ]
  },
  longStatus:{
    ModbusConnect:0,
    ExternIOConnect:1,
  }
}